### ISSUE TITLE
Requests time out after only 10 seconds

### ISSUE THREAD

**Issue by juhovan** [FireMasterK/http3-ytproxy#1]
Hello,

https://github.com/FireMasterK/http3-ytproxy/blob/main/main.go#L198 is causing requests to time out after only 10 seconds which sometimes isn't enough.
For some reason I'm not seeing this on the https://piped.kavin.rocks/ instance, but I fixed it on my own by changing this line.
My own instance is set up pretty much by following https://piped-docs.kavin.rocks/docs/self-hosting/.

![image](https://user-images.githubusercontent.com/6834766/127784791-57a6fad7-f80b-4c94-ac9f-3a1e5002852d.png)

**Comment by FireMasterK** [comment]
You're right, that's the correct thing to change.

> WriteTimeout normally covers the time from the end of the request header read to the end of the response write (a.k.a. the lifetime of the ServeHTTP), by calling SetWriteDeadline at the end of readRequest.

I think something like 30 seconds would be better, but at this point - is it really usable? Wouldn't your experience be downright terrible? I feel that even 10 seconds is a long time for a dash request!

**Comment by juhovan** [comment]
It's indeed terrible when requests take that long, but for some reason that happens with some videos, also on the official instance. Here's waterfall for https://piped.kavin.rocks/watch?v=07Z4iL8hy1A : 
![image](https://user-images.githubusercontent.com/6834766/127888969-742b95cd-b8e1-4026-ae1b-798fc19c74e2.png)
As you can see there's one request that takes almost 30s in the middle of good ones, which is not a problem if we have enough buffer, and my experience with my own instance is that if requests start hitting timeout it won't fix itself but gets stuck retrying the same request. Unfortunately it seems that video is now fast on my own instance so I can't get a picture of waterfall for that.

So I'm thinking setting it to 30seconds would be worth trying, it seems to work fine for me at least and apparently that's how it works on the official instance anyway (Is it not using this proxy?)

**Comment by FireMasterK** [comment]
I would like to investigate this further first before I make such a change.
I took a URL and ran the following: `wget --limit-rate 10k https://pipedproxy-bom...` and never once did the server disconnect the client for taking too long.

**Comment by juhovan** [comment]
I looked into this a bunch more and figured that my reverse proxy (apache) that I have in front of everything was using http/1.1 while other instances are http/2 so I configured it to use http/2 and I have no idea what's going on anymore:
- http/2 now times out at first test: 7minutes 22seconds, seconds test: 4minutes 59seconds
- http/1.1 times out at first test: 3minutes, seconds test: 3minutes and 57seconds

Reducing limit-rate to 1k doesn't seem to make a difference.

It's very puzzling that it changed for http/1.1 since the backend connection is http/1.1 still, but I guess it's safe to say this is somehow triggered only in my setup and seems to work ok-ish now so I'll close this.

Thanks for the replies, it's a nice project :+1:
